# Generated by pip2nix 0.8.0.dev1
# Adjust to your needs, e.g. to provide C libraries.

{ pkgs, basePythonPackages }:

self: super: {

  # Example adjustment for lxml: It needs a few C libraries
  #
  # lxml = super.lxml.override (attrs: {
  #   buildInputs = with self; [
  #     pkgs.libxml2
  #     pkgs.libxslt
  #   ];
  # });

  psycopg2 = super.psycopg2.override (attrs: {
    nativeBuildInputs = with self; [
      pkgs.postgresql_12
    ];
  });

  # Common needs

  # setuptools - avoid that we end up in a recursion
  # inherit (basePythonPackages) setuptools;

}
