# Scaffold generated by pip2nix 0.8.0.dev1

{ pkgs ? import ./nix {}
, pythonPackages ? "python38Packages"
}:

let
  inherit (pkgs.lib) fix extends;

  basePythonPackages = with builtins; if isAttrs pythonPackages
    then pythonPackages
    else getAttr pythonPackages pkgs;

  pythonPackagesGenerated = pkgs.callPackage ./nix/python-packages.nix {};
  pythonPackagesOverrides = pkgs.callPackage ./nix/python-packages-overrides.nix { inherit basePythonPackages; };

  pythonPackagesLocalOverrides = self: super: {
    hello = super.buildPythonApplication {
      pname = "hello";
      version = "1.0";
      src = pkgs.gitignoreSource ./.;
      propagatedBuildInputs = [
        self.tqdm
        self.psycopg2
      ];
      passthru = {
        pythonPackages = myPythonPackages;
      };
    };
  };

  myPythonPackages =
    (fix
    (extends pythonPackagesLocalOverrides
    (extends pythonPackagesOverrides
    (extends pythonPackagesGenerated
             basePythonPackages.__unfix__))));

in myPythonPackages.hello
